services:

  postgres:
    image: pgvector/pgvector:pg17
    container_name: postgres

    environment:
      POSTGRES_DB: rag_search
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


  ollama:
    image: ollama/ollama
    container_name: ollama

    runtime: nvidia

    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility

    ports:
      - "11434:11434"

    volumes:
      - ollama_data:/root/.ollama


volumes:
  postgres_data:
  ollama_data: