spring.application.name=rag-search

spring.profiles.active=dev

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

ollama.url=${OLLAMA_URL}
ollama.chat-model=${OLLAMA_CHAT_MODEL}
ollama.embedding-model=${OLLAMA_EMBEDDING_MODEL}

rag.embedding.batch-size=64